# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160910_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(default=2332),
            preserve_default=False,
        ),
    ]
